# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:latest

RUN sudo apt-get install -y python3-pip apt-utils
RUN pip install Inject==3.5.4 awsiotsdk pydub
#RUN pip install   simpleaudio

RUN git clone https://github.com/mangdangroboticsclub/mini_pupper_2_bsp /tmp/mini_pupper_2_bsp

# Set the working directory to the Python package directory
WORKDIR /tmp/mini_pupper_2_bsp/Python_Module
# Install Python dependencies from requirements.txt if available
RUN pip install -r requirements.txt


ADD robot_ws/src /home/robomaker/workspace/robot_ws/src
ADD robot_ws/src/mini_pupper_ros/mini_pupper_dance/routines /home/robomaker/mini-pupper-aws/routines
ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
RUN sudo rosdep fix-permissions && rosdep update --include-eol-distros

WORKDIR /home/robomaker/workspace/robot_ws


# Build the Robot application
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y  && colcon build && sudo apt clean"

# Add entrypoint script and grant permission
COPY scripts/robot-entrypoint.sh robot-entrypoint.sh
RUN sh -c 'sudo chmod +x robot-entrypoint.sh && sudo chown robomaker:robomaker robot-entrypoint.sh'

RUN sudo mkdir -p /config/certs/

# xterm for interactive debug
RUN sudo apt install -y xterm

CMD ros2 launch mini_pupper_dance enhanced_dance.launch.py  hardware_connected:=false
ENTRYPOINT [ "/home/robomaker/workspace/robot_ws/robot-entrypoint.sh" ]
