# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:2.0

ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
ADD robot_ws/src /home/robomaker/workspace/robot_ws/src
RUN sudo rosdep fix-permissions && rosdep update  --include-eol-distros

# because of dependency on mini_pupper_description, build robot_ws
WORKDIR /home/robomaker/workspace/robot_ws

# Build the Robot application
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y && colcon build && sudo apt clean"

WORKDIR /home/robomaker/workspace/simulation_ws

RUN sudo apt install ros-noetic-gazebo-* ros-noetic-ros-control -y

# Build the Robot application
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y && colcon build --cmake-args '-Wno-dev' && sudo apt clean"
# Change log leven to debug
# RUN sudo sed -i 's/INFO/DEBUG/' /opt/ros/noetic/share/ros/config/rosconsole.config

# Add entrypoint script and grant permission
COPY scripts/simulation-entrypoint.sh simulation-entrypoint.sh
RUN sh -c 'sudo chmod +x simulation-entrypoint.sh && sudo chown robomaker:robomaker simulation-entrypoint.sh'

# xterm for interactive debug
RUN sudo apt install -y xterm

CMD roslaunch mini_pupper_simulation aws_stage.launch
ENTRYPOINT [ "/home/robomaker/workspace/simulation_ws/simulation-entrypoint.sh" ]
