# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:latest

RUN sudo apt-get install -y python3-pip apt-utils
RUN pip install Inject==3.5.4

ADD robot_ws/src /home/robomaker/workspace/robot_ws/src
ADD robot_ws/src/mini_pupper_ros/mini_pupper_dance/routines /home/robomaker/mini-pupper-aws/routines
ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
RUN sudo rosdep fix-permissions && rosdep update --include-eol-distros

WORKDIR /home/robomaker/workspace/robot_ws


# Build the Robot application
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y  && colcon build && sudo apt clean"

# Add entrypoint script and grant permission
COPY scripts/robomaker-entrypoint.sh robomaker-entrypoint.sh
RUN sh -c 'sudo chmod +x robomaker-entrypoint.sh && sudo chown robomaker:robomaker robomaker-entrypoint.sh'

COPY scripts/dancemove.sh dancemove.sh
RUN sh -c 'sudo chmod +x dancemove.sh && sudo chown robomaker:robomaker dancemove.sh'

RUN sudo mkdir -p /config/certs/

# xterm for interactive debug
RUN sudo apt install -y xterm

CMD ros2 launch mini_pupper_dance ndance.launch.py hardware_connected:=false
ENTRYPOINT [ "/home/robomaker/workspace/robot_ws/robomaker-entrypoint.sh" ]
