# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
FROM ros:humble

ENV DEBIAN_FRONTEND noninteractive
# Install common dependency and ROS tools
RUN apt-get update && apt-get install -y \
    lsb  \
    unzip \
    wget \
    xterm \
    curl \
    sudo \
    python3-vcstool \
    python3-rosinstall-generator \
    python3-colcon-common-extensions \
    sphinxsearch \
    devilspie \
    xfce4-terminal

ENV QT_X11_NO_MITSHM=1
# Install Gazebo 11
RUN curl -sSL http://get.gazebosim.org | sh
#RUN wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -; \
#    sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-humble `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-humble.list' && \
#    apt-get update && apt-get install -y gazebo11 && apt-get clean

# Create user to reduce privilege
ARG USERNAME=robomaker
RUN groupadd $USERNAME && \
    useradd -ms /bin/bash -g $USERNAME $USERNAME && \
    sh -c 'echo "$USERNAME ALL=(root) NOPASSWD:ALL" >> /etc/sudoers'
    
# Switch to newly created user    
USER $USERNAME
RUN sh -c 'cd /home/$USERNAME'

# Copy our Robot and Simulation application
RUN sh -c 'mkdir -p /home/robomaker/workspace/robot_ws/src && mkdir -p /home/robomaker/workspace/simulation_ws/src && cd /home/robomaker/workspace'
