# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:2.0

ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
RUN sudo apt install python3-rosdep2 -y
RUN sudo rosdep fix-permissions && rosdep update  --include-eol-distros

# because of dependency on mini_pupper_description, build robot_ws
WORKDIR /home/robomaker/workspace/simulation_ws

RUN sudo apt install ros-humble-teleop-twist-keyboard -y

# Build the Robot application
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && rosdep install --rosdistro humble --from-paths src --ignore-src -r -y && colcon build --cmake-args '-Wno-dev' && sudo apt clean"
# Change log leven to debug
# RUN sudo sed -i 's/INFO/DEBUG/' /opt/ros/humble/share/ros/config/rosconsole.config

# Add entrypoint script and grant permission
COPY scripts/simulation-entrypoint.sh simulation-entrypoint.sh
RUN sh -c 'sudo chmod +x simulation-entrypoint.sh && sudo chown robomaker:robomaker simulation-entrypoint.sh'
COPY scripts/move.sh move.sh
RUN sh -c 'sudo chmod +x move.sh && sudo chown robomaker:robomaker move.sh'

# xterm for interactive debug
RUN sudo apt install -y xterm

#CMD roslaunch mini_pupper_simulation aws_stage.launch
ENTRYPOINT [ "/home/robomaker/workspace/simulation_ws/simulation-entrypoint.sh" ]
